### ISSUE TITLE
Please remove enotty.dk

### ISSUE THREAD

**Issue by kseistrup** [tkanos/we-are-twtxt#1]
There haven't been any active twtxt accounts on `enotty.dk` for a couple of years. Please specifically remove:

```
https://enotty.dk/twtxt.txt
```

and please never add any `enotty.dk` URLs in the future. Thanks.

**Comment by tkanos** [comment]
Hello M Kas, 

Of course I can remove it, you were listed as an influencer of twtxt community.
Doing the necessary to don't list you anymore, but without blacklisting you in the code (it will be counter productive to list you in the code to don't list you :D)

**Comment by kseistrup** [comment]
It could be a never-ending task to contact each and every twtxt client developer to have my URLs removed from the codebase.

And anyway, I came here because of the User-Agent string `twx/{0.1.0 (+crawler; @https://github.com/tkanos/we-are-twtxt)`.

**Comment by tkanos** [comment]
No way, I was wondering how you did so fast.
What is the solution you use behind to be alerted by the crawler ?

**Comment by kseistrup** [comment]
I was just casually looking through my webserver log and I noticed several requests for `/twtxt.txt` from the same IP address with the same User-Agent within a very short time and I decided to stop the madness while it was still hot.
